### PR TITLE
Revised geostrophic streamfunction and velocity functions

### PR DESCRIPTION
**Pull request by efiring**
This incorporates the changes in https://github.com/TEOS-10/GSW-C/pull/20.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@efiring the c changes are the same in your PR upstream, right? I am :+1: to merge this here before upstream is resolved. (Just hit that bug and had to revert to the an old pure Python version :unamused:)

**Comment by efiring** [comment]
@ocefpaf Yes, the C part here is exactly the current state of the C PR. I think this is ready to merge, and I expect the C PR will also be merged soon.  Any additional changes to the C can be handled in subsequent PRs, as can version number changing, docs improvements, etc.

**Comment by ocefpaf** [comment]
@efiring I am preparing a new release with this change. Is that OK with you or do you want to hold the trigger for a while?

**Comment by efiring** [comment]
You are welcome to proceed, thank you.

**Pull request merged**
