### PR TITLE
Dev notes

### LINKED ISSUE #129: Add a "Development Instructions" README/Docs
Currently we only have this note in our README:

    It is neither necessary nor recommended to run the code generators, and no instructions are provided for them;
    their output is included in the repo.

While I agree that the average user should not do that, we need to document those steps if we wish to lower the barrier for new developers.

It should be as simple as "promoting" the `tools/README.txt` to a first class citizen in our docs and/or linking it in our `README.md`.

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes #129

- [x] Add a note about the matlab code for docstring parsing
- [x] Add a note about the C code for func parsing

### CODE REVIEW

**Comment by ocefpaf** [comment]
@efiring I want to incorporate this into our docs and test the process myself but I'll leave that to another PR. Do you mind taking a quick look if you have some free time?

**Comment by efiring** [comment]
Thank you. Sorry to have forgotten about this, long ago.  I will try to review it in the next few days.

**Comment by efiring** [comment]
I will leave it to you to merge when you are ready.

**Comment by ocefpaf** [comment]
Thanks! I'll tackle the HTML docs in another PR. Let's get this one in so others have some breadcrumbs to follow when contributing to this repo.

**Pull request merged**
