### PR TITLE
Take 2

### PR DESCRIPTION
**Pull request by ocefpaf**
@efiring I cannot do more b/c I still do not have all the rights here, sigh. Oh well. If you can create the PyPI token and encrypt it on Travis-CI we can move forward with the building and publishing wheels.

### CODE REVIEW

**Comment by efiring** [comment]
When I look at the "Manage Access" tab of settings, it looks like you and I have the same access.  Who needs to do what in order to give you the rights you need?

**Comment by durack1** [comment]
@efiring looks like you're one bump up on @ocefpaf (you're an owner, whereas @ocefpaf is a member) https://github.com/orgs/TEOS-10/people

**Comment by ocefpaf** [comment]
Everything is passing and we have wheels on Windows, macOS and Linux! The source distribution is still published via Travis-CI.

@efiring once we add the tokens I need to uncomment the upload part and change this to run only when there is a tag.

**Comment by ocefpaf** [comment]
If I read all the logs correctly are are failing, as expected, b/c the secrets are not available in PRs from forks. I'll merge this and issue a new tag just to test it. If it does not work I'll tweak it without using a fork.

**Pull request merged**
