### PR TITLE
Add infunnel wrapper, simplify code generation

### PR DESCRIPTION
**Pull request by efiring**
Wrapping the infunnel function, with its int return, required enough change that I took the opportunity to re-write some of the code generation functions.

### CODE REVIEW

**Comment by efiring** [comment]
You already have one CI run for code generation--do you mean run code generation for every build on every combination of versions and platforms? I'm not convinced that would be a good idea.

**Comment by ocefpaf** [comment]
> You already have one CI run for code generation--do you mean run code generation for every build on every combination of versions and platforms? I'm not convinced that would be a good idea.

Nope. I forgot I already did that :-/
Sorry but lately my brain doesn't seem to be able to hold new information anymore.

**Comment by ocefpaf** [comment]
@efiring are you OK with a new release? I can do that later today/tomorrow.

**Comment by efiring** [comment]
Yes, a release would be fine, thank you.

**Pull request merged**
