### PR TITLE
Move to cibuildwheels

### PR DESCRIPTION
**Pull request by ocefpaf**
Not ready for review yet.

### CODE REVIEW

**Comment by DocOtak** [comment]
Awesome, I hope this works well.

**Comment by ocefpaf** [comment]
@efiring and @DocOtak I'd love a second set of eyes here. This will move our clunky way of building wheels to the modern cibuildwheel It also builds wheels for the M1/M2 chips and the unreleased Python 3.11 (thanks to the stable API we can build wheels using the RCs now).

**Comment by DocOtak** [comment]
I grabbed the build artifacts and tested the python 3.9 and 3.10 wheels on the metal of my M1 machine (no rosetta). Everything Just Worked™, even the tests pass which I didn't expect passing given the fun in #40.

**Comment by efiring** [comment]
I tested the python3.10 wheel on macosx x86-64, and that also passes.  Looks good.  The only question I have at this point is why the artifacts include Python 3.6 and 3.7.  I think we can drop those now.

**Comment by ocefpaf** [comment]
> The only question I have at this point is why the artifacts include Python 3.6 and 3.7. I think we can drop those now.

Indeed. I left the cibuildwheels defaults there and they deprecated things a bit slower than the official deprecation. GSW in the other hand kind of follow NEP29 b/c the numpy dependency. Dropping those now.

**Review by efiring — APPROVED** [review]

**Pull request merged**
