### PR TITLE
build wheel for Python 3.9

### PR DESCRIPTION
**Pull request by ocefpaf**
Avoid compilation when installing with pip on Python 3.9. See https://github.com/TEOS-10/GSW-Python/issues/78

### CODE REVIEW

**Comment by efiring** [comment]
I think we should drop 3.6 while adding 3.7, shouldn't we?

**Comment by ocefpaf** [comment]
> I think we should drop 3.6 while adding 3.7, shouldn't we?

Makes sense. We already dropped 3.6 from testing. Although we do build with an old numpy for "forward compatibility."

I'm just waiting for the tests to pass to make the GHA run only on published tags. We'll have to issue a `.post0` version to generate the wheel.

**Comment by DocOtak** [comment]
Would it make sense to follow [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) re python/numpy support?

**Comment by ocefpaf** [comment]
> Would it make sense to follow [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) re python/numpy support?

We kind of do already. numpy 1.18 was dropped this past month but we don't have to rush to 1.19 just yet. Note that the users will get the latest numpy, just the build is with an old one to ensure compatibility.

We can move to 1.19 when we have a new release of gsw, in a way, we are just "catching up" with old releases here by building the wheels.

**Review by efiring — APPROVED** [review]
Looks reasonable, passes the tests.

**Pull request merged**
