### PR TITLE
Adding Gibbs

### LINKED ISSUE #131: add missing functions (gibbs etc)
Hello,

I was about to comment the #130 but you closed it before I could. I'm reopening an issue on the topic:

do you think it's worth I submit a PR to add gibbs to the package ?

My motivation. This morning my solution to include 'gibbs'  was a bit ugly. I've cleaned it. It is now very simple and it works well for gibbs. I can see that it could quite easily be generalized to the other missing functions.

### PR DESCRIPTION
**Pull request by pvthinker**
This PR resolves #131

Algo: use ctypes to import the compiled function that is present in the dynamic library [suffix .so on Linux]

then call the function with the float passed into `ctypes.c_double()`

### CODE REVIEW

**Comment by efiring** [comment]
This approach abandons the advantages of a ufunc, and drops back to using a Python loop to call the compiled function.  Broadcasting could be added in the Python function, but the Python-level looping would remain. I would much rather take a little time to explore alternatives that keep the gibbs implementations closer to the bulk of the library. The ctypes method can be used outside the library in the interim.

**Comment by pvthinker** [comment]
We can make 'gibbs' a ufunc with the help of 'numpy.frompyfunc'.

This works fine but the __doc__ is lost by frompyfunc, which forces the default numpy.ufunc __doc__. I didn't manage to circumvent this. The __doc__ attribute of an object return by 'frompyfunc' is unwritable.

Speaking of ufunc, it seems like none of the gsw functions are of 'numpy.ufunc' type. They are simply 'function'. In particular, they don't have the 'out' keyword, that is useful when the result variable has already been allocated because it avoids an unnecessary allocation.

**Comment by DocOtak** [comment]
@efiring why isn't the C gsw_gibbs function already being wrapped by the scripts in tools?

**Comment by efiring** [comment]
I simply did not include signatures with integer arguments; it did not seem necessary, and it adds a level of complexity relative to restricting the machinery to handling the normal user-level functions.  I didn't think anyone would want to call the gibbs function directly; I viewed it as an internal engine, not something that needed to be exposed.  Other than purely utility functions, gibbs and gibbs ice are the only functions in C that are suitable for ufuncs and are not currently handled.  I'm looking into adding them.

**Comment by efiring** [comment]
Thank you for the contribution.  Although I did not merge it, it prompted me to make some needed clarifications
and revisions in the process of coming up with the alternative approach I used in #134.

**Pull request closed without merging**
