### PR TITLE
Fix URLs redirects

### PR DESCRIPTION
**Pull request by ocefpaf**
Testing the URL breakages in #185

### CODE REVIEW

**Comment by ocefpaf** [comment]
@efiring while having accurate URLs in the docs is nice I'm tempted to skip the URL check for now b/c a correct fix should be in the upstream matlab docs, right?

**Comment by efiring** [comment]
@ocefpaf I think the corrections you have in `gsw.rst` and `__init__.py` are where they should be.  for `_wrapped_ufuncs` the corrections should be made by adding entries to `subs` in `fix_wrapped_ufuncs.py`.  It looks like maybe only one additional entry is needed there.

Getting corrections upstream is a reasonable goal for the future, but not something I think we should try right now.

**Comment by efiring** [comment]
Also, I don't understand why some of the teos-10 urls are failing in the test. Both the original `http:` the new `https` versions work in my browser. The test is apparently not allowing the redirect?  In any case, fixing them via the `sub` mechanism makes sense, as far as I can see.

**Comment by ocefpaf** [comment]
Yeah, the redirection works fine in the browser and sporadically when I re-run the tests. I wonder if the 403 is b/c we are hitting that URL multiple times (it is everywhere in the docs).

**Review by efiring — APPROVED** [review]
Good, thank you.

**Pull request merged**
