### PR TITLE
add pre-commit

### PR DESCRIPTION
**Pull request by ocefpaf**
I asked a student to read the docs recently and she pointed out a few typos to me. Decided to add pre-commit codespell to help keep the docs in shape.

### CODE REVIEW

**Comment by efiring** [comment]
The docstrings are mostly taken automatically from the Matlab version, so that's where most of the errors being fixed here originate.  I guess this means that any change involving regenerating them will require a manual run of codespell or pre-commit prior to the last local commit before pushing to Github.

**Comment by ocefpaf** [comment]
> The docstrings are mostly taken automatically from the Matlab version

The student mentioned that to me but that code is not developed on GitHub so we cannot fix them at the source :unamused: 

> I guess this means that any change involving regenerating them will require a manual run of codespell or pre-commit prior to the last local commit before pushing to Github.

pre-commit+codespell can fix those automatically and it can be hooked in a CI but that is cumbersome and can be confusing for new contributors b/c the pre-commit CI commits in the authors branch, usually causing headaches for git novices (and even some experts).

I would prefer to avoid it automating this. I'm more on the side of not merging the typo fixes and codespell check or doing that manually. Let me know which one you prefer.

**Comment by efiring** [comment]
I think the manual approach will be fine with the addition of instructions in the README.  And, typos from the Matlab that are identified this way might be fixed in the Matlab by @PaulMBarker.

**Comment by ocefpaf** [comment]
> I think the manual approach will be fine with the addition of instructions in the README.


Let me know if the instructions are OR.

> And, typos from the Matlab that are identified this way might be fixed in the Matlab by @PaulMBarker.

I'd love to fix those too but the development is not on GitHub yet and fixing the version dumped there won't help much :-/

**Comment by ocefpaf** [comment]
I'm planning on a new post release and docs. Merging this as soon as it passes so we can make the docs a bit more pleasant to read.

**Pull request merged**
