### PR TITLE
Closes 74

### PR DESCRIPTION
**Pull request by ocefpaf**
Added a test to avoid regressions and pinned pandas to >=2 in our tests.
Note that pandas is not a direct dependency of `gsw` so in a way that bug is only fixed if the user updates their pandas.

I also moved all the metadata from `setup.cfg` to `pyproject.toml` to help consolidate the packaging with less files and a more modern approach. I'll try to do the same for the `setup.py` in a future PR. but compiled extensions are still hard to do in a consistent manner.

PS: I'll fix the lints in another PR this one is already too big for its own sake.

### CODE REVIEW

**Comment by efiring** [comment]
It looks like ruff is finding some legacy things that could be cleaned up (but that don't hurt, so they are very low priority), and some things we probably don't want to change at all.  Maybe the thing to do is to turn ruff off for now, so the rest of this changeset can be merged without leaving behind perpetual test failure.

**Comment by ocefpaf** [comment]
>  without leaving behind perpetual test failure.

I'm planning on working on this as soon as this one is merged. I already have the changes locally, from fixes to file/test skips. Hopefully the failure won't be there for more than a day. But I can turn it off, merge and on again, no problem.

**Review by efiring — APPROVED** [review]
Fine to go ahead with this as is.

**Comment by ocefpaf** [comment]
> Fine to go ahead with this as is.

I pushed [them here](https://github.com/TEOS-10/GSW-Python/pull/127) in case you have some free cycles to look at them (last commit)  of https://github.com/TEOS-10/GSW-Python/pull/127

**Comment by ocefpaf** [comment]
Follow up in #127. I don't want to make this PR too big and hard to follow.

**Pull request merged**
